# ~/.config/fuzzel/fuzzel.ini

[main]
font=Monospace:size=12
dpi-aware=yes

[border]
width=2
radius=8

[colors]
background=2e3440ff      
text=d8dee9ff            
selection=3b4252ff      
selection-text=d8dee9ff 
border=4c566aff         
