preload = /home/kevlar/Pictures/wallpapers/jocker.jpg
wallpaper = ,/home/kevlar/Pictures/wallpapers/jocker.jpg
# preload = /home/kevlar/Pictures/wallpapers/naughty.png
# wallpaper = ,/home/kevlar/Pictures/wallpapers/naughty.png
