preload = ~/Pictures/wallpapers/makima.jpg
preload = ~/Pictures/wallpapers/crying_vscode.jpg
preload = ~/Pictures/wallpapers/javascript.jpg
preload = ~/Pictures/wallpapers/omao_1.jpg
preload = ~/Pictures/wallpapers/onlyfans.png
wallpaper = , ~/Pictures/wallpapers/makima.jpg
