preload = /home/kevlar/Pictures/wallpapers/black-hole.png
wallpaper = ,/home/kevlar/Pictures/wallpapers/black-hole.png
# preload = /home/kevlar/Pictures/wallpapers/naughty.png
# wallpaper = ,/home/kevlar/Pictures/wallpapers/naughty.png
