# Change if not using kitty 
set-option -g default-terminal "xterm-kitty"
set -ga terminal-overrides ",xterm-kitty:Tc"
set -s escape-time 0

unbind C-b
set-option -g prefix C-space
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'
set-option -g mouse on
set-option -g base-index 1
setw -g pane-base-index 1





# Set the default shell
# set-option -g default-shell /bin/bash

# Enable status bar with customization
# set-option -g status on
# set-option -g status-bg black
# set-option -g status-fg white

# Shortcuts for pane splitting
# bind | split-window -h
# bind - split-window -v
# unbind '"'
# unbind %

# Enable easier pane navigation
# bind h select-pane -L
# bind j select-pane -D
# bind k select-pane -U
# bind l select-pane -R

# Reload tmux config without restarting
# bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Aesthetic settings
# set-option -g pane-border-style fg=cyan
# set-option -g pane-active-border-style fg=green

# Set history limit
# set-option -g history-limit 10000

