#include ./themes/rose-pine/rose-pine-moon.conf
include ./themes/rose-pine/rose-pine.conf
#include ./themes/catppuccin/mocha.conf
#include ./themes/kitty-themes/MaterialDark.conf

#font_family FiraCode Nerd Font
font_family JetBrainsMonoNL Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12
cursor_shape block
cursor_blink_interval 0


disable_ligatures always
enable_audio_bell no

copy_on_select yes

#background_opacity 0.9
